version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "8000:80"
    volumes:
      - ./web_root:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_user_password
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
