version: '3'
services:
  web:
    image: php:7.4-apache-mysqli
    ports:
      - "8000:80"
    volumes:
      - ./web_root:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root2023
      MYSQL_DATABASE: mydb
      MYSQL_USER: bruce
      MYSQL_PASSWORD: bruce2023
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
