version: '3'
services:
  chatgpt:
    image: pengzhile/pandora
    container_name: chat-openai
    environment:
      - PANDORA_CLOUD=cloud
      - PANDORA_SERVER=0.0.0.0:8899
    ports:
      - "8899:8899"
    restart: always